/**
 * Pokopia Companion — static game data
 * Foods / flavors: Serebii Pokopia flavors list (+ community Mosslax notes).
 * Fossils: 22 pieces across 9 museum displays (community museum guides).
 */
window.POKOPIA_DATA = {
  flavors: [
    {
      id: "neutral",
      name: "Neutral",
      color: "#7eb8a2",
      mosslax: "Bond with Pokémon faster (comfort / friendship).",
    },
    {
      id: "sweet",
      name: "Sweet",
      color: "#e89bb8",
      mosslax: "More Ancient Artifact glow spots (fossils, relics, slates).",
    },
    {
      id: "spicy",
      name: "Spicy",
      color: "#e07a5f",
      mosslax: "Pokémon appear more often in habitats (great for the Pokédex).",
    },
    {
      id: "dry",
      name: "Dry",
      color: "#c4a574",
      mosslax: "Ho-Oh & Lugia more likely to drop Mysterious Feathers.",
    },
    {
      id: "bitter",
      name: "Bitter",
      color: "#6b8f71",
      mosslax: "Better chance of finding rare items.",
    },
    {
      id: "sour",
      name: "Sour",
      color: "#e9c46a",
      mosslax: "Trade shops more likely to stock good items.",
    },
  ],

  /**
   * Example Pokémon that have cooking-relevant specialties (not exhaustive).
   * Partner must be following you or near the cooking station.
   */
  specialtyHelpers: {
    Chop: ["Scyther", "Scizor", "Pinsir", "Heracross"],
    Crush: ["Onix", "Steelix", "Golem", "Conkeldurr"],
    Generate: ["Magnemite", "Magneton", "Pikachu", "Mareep"],
    Burn: ["Charmander", "Vulpix", "Torkoal", "Growlithe"],
    Water: ["Squirtle", "Psyduck", "Lotad", "Vaporeon"],
    Recycle: ["Magnezone", "Trubbish", "Garbodor", "Weezing"],
    Explode: ["Voltorb", "Electrode"],
    Party: ["Chef Dente"],
  },

  foods: [
    // Neutral
    { id: "leppa-berry", name: "Leppa Berry", flavor: "neutral", kind: "Berry", note: "Berry trees", recipe: null },
    { id: "lum-berry", name: "Lum Berry", flavor: "neutral", kind: "Berry", note: "Berry trees", recipe: null },
    { id: "fresh-water", name: "Fresh Water", flavor: "neutral", kind: "Drink", note: "Environment / vending", recipe: null },
    { id: "bruised-berry", name: "Bruised Berry", flavor: "neutral", kind: "Other", note: "From Chef Dente", recipe: null },
    {
      id: "simple-salad",
      name: "Simple Salad",
      flavor: "neutral",
      kind: "Cooked",
      note: "Ordinary leaf salad",
      recipe: { station: "Chopping Board", ingredients: ["Leaf ×1", "Any ×1"], specialty: null },
    },
    {
      id: "simple-soup",
      name: "Simple Soup",
      flavor: "neutral",
      kind: "Cooked",
      note: "Fresh Water soup",
      recipe: { station: "Cooking Pot (on Stove)", ingredients: ["Fresh Water ×1", "Any ×2"], specialty: null },
    },
    {
      id: "simple-bread",
      name: "Simple Bread",
      flavor: "neutral",
      kind: "Cooked",
      note: "Ordinary wheat bread",
      recipe: { station: "Bread Oven", ingredients: ["Wheat ×1", "Any ×2"], specialty: null, tip: "Oven needs a Burn Pokémon nearby to power on." },
    },
    {
      id: "simple-hamburger",
      name: "Simple Hamburger Steak",
      flavor: "neutral",
      kind: "Cooked",
      note: "Bean hamburger",
      recipe: { station: "Frying Pan (on Stove)", ingredients: ["Bean ×1", "Any ×3"], specialty: null },
    },
    {
      id: "vibrant-hamburger",
      name: "Vibrant Hamburger Steak",
      flavor: "neutral",
      kind: "Cooked",
      note: "Lots of ingredients",
      recipe: { station: "Frying Pan (on Stove)", ingredients: ["Bean ×1", "Simple Salad ×1", "Potato ×1"], specialty: null },
    },
    {
      id: "curry-and-rice",
      name: "Curry and Rice",
      flavor: "neutral",
      kind: "Cooked",
      note: "Party meal with other Pokémon",
      recipe: { station: "Special / party cooking", ingredients: ["Varies — party meal with other Pokémon"], specialty: "Party", tip: "Made as a group meal rather than a standard station recipe." },
    },

    // Sweet
    { id: "pecha-berry", name: "Pecha Berry", flavor: "sweet", kind: "Berry", note: "Berry trees", recipe: null },
    { id: "bean", name: "Bean", flavor: "sweet", kind: "Veggie", note: "Plant & harvest", recipe: null },
    { id: "moomoo-coffee", name: "Moomoo Milk Coffee", flavor: "sweet", kind: "Drink", note: "Shop / vending", recipe: null },
    { id: "common-candy", name: "Common Candy", flavor: "sweet", kind: "Other", note: "From Chef Dente", recipe: null },
    { id: "rare-candy", name: "Rare Candy", flavor: "sweet", kind: "Other", note: "From Chef Dente", recipe: null },
    { id: "watermelon-slice", name: "Watermelon Slice", flavor: "sweet", kind: "Veggie", note: "DLC / special harvest", recipe: null, dlc: true },
    {
      id: "leppa-salad",
      name: "Leppa Salad",
      flavor: "sweet",
      kind: "Cooked",
      note: "Salad with Leppa Berries",
      recipe: { station: "Chopping Board", ingredients: ["Leaf ×1", "Leppa Berry ×1"], specialty: null },
    },
    {
      id: "fluffy-bread",
      name: "Fluffy Bread",
      flavor: "sweet",
      kind: "Cooked",
      note: "Pecha Berry bread",
      recipe: { station: "Bread Oven", ingredients: ["Wheat ×1", "Pecha Berry ×1", "Any ×1"], specialty: "Water" },
    },
    {
      id: "watermelon-bread",
      name: "Watermelon Bread",
      flavor: "sweet",
      kind: "Cooked",
      note: "Watermelon bread",
      dlc: true,
      recipe: { station: "Bread Oven", ingredients: ["Wheat ×1", "Watermelon Slice ×1"], specialty: null, tip: "Bubbly Basin DLC." },
    },
    {
      id: "potato-hamburger",
      name: "Potato Hamburger Steak",
      flavor: "sweet",
      kind: "Cooked",
      note: "Sweet hamburger steak",
      recipe: { station: "Frying Pan (on Stove)", ingredients: ["Bean ×1", "Potato ×1", "Any ×2"], specialty: null },
    },
    {
      id: "leppa-smoothie",
      name: "Leppa Smoothie",
      flavor: "sweet",
      kind: "Drink",
      note: "Powers up Surf",
      dlc: true,
      recipe: { station: "Blender", ingredients: ["Watermelon Slice ×1", "Leppa Berry ×1", "Any ×1"], specialty: null, tip: "Bubbly Basin DLC — unlock blender via Mudkip." },
    },
    {
      id: "watermelon-smoothie",
      name: "Watermelon Smoothie",
      flavor: "sweet",
      kind: "Drink",
      note: "Powers up Surf",
      dlc: true,
      recipe: { station: "Blender", ingredients: ["Watermelon Slice ×1", "Any ×2"], specialty: null, tip: "Bubbly Basin DLC — unlock blender via Mudkip." },
    },

    // Spicy
    { id: "fresh-carrot", name: "Fresh Carrot", flavor: "spicy", kind: "Veggie", note: "Pull leaves from the ground", recipe: null },
    { id: "chili-sauce", name: "Chili Sauce", flavor: "spicy", kind: "Drink", note: "Shop / vending", recipe: null },
    {
      id: "crouton-salad",
      name: "Crouton Salad",
      flavor: "spicy",
      kind: "Cooked",
      note: "Crunchy salad",
      recipe: { station: "Chopping Board", ingredients: ["Leaf ×1", "Bread ×1 (any)"], specialty: null },
    },
    {
      id: "electrifying-soup",
      name: "Electrifying Soup",
      flavor: "spicy",
      kind: "Cooked",
      note: "Shockingly spicy",
      recipe: { station: "Cooking Pot (on Stove)", ingredients: ["Fresh Water ×1", "Any ×2"], specialty: "Generate" },
    },
    {
      id: "healthy-soup",
      name: "Healthy Soup",
      flavor: "spicy",
      kind: "Cooked",
      note: "Aromatic bean flavor",
      recipe: { station: "Cooking Pot (on Stove)", ingredients: ["Fresh Water ×1", "Bean ×1", "Leaf ×1"], specialty: null },
    },
    {
      id: "carrot-bread",
      name: "Carrot Bread",
      flavor: "spicy",
      kind: "Cooked",
      note: "Intense carrot flavor",
      recipe: { station: "Bread Oven", ingredients: ["Wheat ×1", "Fresh Carrot ×1", "Any ×1"], specialty: null },
    },
    {
      id: "bread-bowl",
      name: "Bread Bowl",
      flavor: "spicy",
      kind: "Cooked",
      note: "Good even when burnt",
      recipe: { station: "Bread Oven", ingredients: ["Wheat ×1", "Soup ×1 (any)", "Any ×1"], specialty: "Burn" },
    },
    {
      id: "explosive-hamburger",
      name: "Explosive Hamburger Steak",
      flavor: "spicy",
      kind: "Cooked",
      note: "Very spicy hamburger",
      dlc: true,
      recipe: { station: "Frying Pan (on Stove)", ingredients: ["Bean ×1", "Sea Grapes ×1", "Chili Sauce ×1"], specialty: "Explode", tip: "Uses Sea Grapes (Bubbly Basin DLC)." },
    },
    {
      id: "red-hot-smoothie",
      name: "Red-hot Smoothie",
      flavor: "spicy",
      kind: "Drink",
      note: "Powers up Surf",
      dlc: true,
      recipe: { station: "Blender", ingredients: ["Watermelon Slice ×1", "Fresh Carrot ×1", "Any ×1"], specialty: "Burn", tip: "Bubbly Basin DLC." },
    },

    // Dry
    { id: "chesto-berry", name: "Chesto Berry", flavor: "dry", kind: "Berry", note: "Berry trees", recipe: null },
    { id: "wheat", name: "Wheat", flavor: "dry", kind: "Veggie", note: "Plant & harvest (edible raw)", recipe: null },
    { id: "cave-mushrooms", name: "Cave Mushrooms", flavor: "dry", kind: "Veggie", note: "Caves & shady spots", recipe: null },
    { id: "roserade-tea", name: "Roserade Tea", flavor: "dry", kind: "Drink", note: "Shop / vending", recipe: null },
    {
      id: "crushed-berry-salad",
      name: "Crushed-berry Salad",
      flavor: "dry",
      kind: "Cooked",
      note: "Crushed Chesto Berries",
      recipe: { station: "Chopping Board", ingredients: ["Leaf ×1", "Chesto Berry ×1"], specialty: "Crush" },
    },
    {
      id: "mushroom-soup",
      name: "Mushroom Soup",
      flavor: "dry",
      kind: "Cooked",
      note: "Mushroom broth",
      recipe: { station: "Cooking Pot (on Stove)", ingredients: ["Fresh Water ×1", "Cave Mushrooms ×1", "Any ×1"], specialty: null },
    },
    {
      id: "mushroom-hamburger",
      name: "Mushroom Hamburger Steak",
      flavor: "dry",
      kind: "Cooked",
      note: "Dry mushroom flavor",
      recipe: { station: "Frying Pan (on Stove)", ingredients: ["Bean ×1", "Cave Mushrooms ×1", "Any ×2"], specialty: null },
    },
    {
      id: "sea-grape-smoothie",
      name: "Sea Grape Smoothie",
      flavor: "dry",
      kind: "Drink",
      note: "Powers up Surf",
      dlc: true,
      recipe: { station: "Blender", ingredients: ["Watermelon Slice ×1", "Sea Grapes ×1", "Any ×1"], specialty: null, tip: "Bubbly Basin DLC." },
    },

    // Bitter
    { id: "rawst-berry", name: "Rawst Berry", flavor: "bitter", kind: "Berry", note: "Berry trees", recipe: null },
    { id: "potato", name: "Potato", flavor: "bitter", kind: "Veggie", note: "Plant & harvest", recipe: null },
    { id: "seaweed", name: "Seaweed", flavor: "bitter", kind: "Veggie", note: "Washed ashore on beaches", recipe: null },
    { id: "sea-grapes", name: "Sea Grapes", flavor: "bitter", kind: "Veggie", note: "Ocean / DLC", recipe: null, dlc: true },
    {
      id: "seaweed-salad",
      name: "Seaweed Salad",
      flavor: "bitter",
      kind: "Cooked",
      note: "Bitter seaweed salad",
      recipe: { station: "Chopping Board", ingredients: ["Leaf ×1", "Seaweed ×1"], specialty: null },
    },
    {
      id: "popping-salad",
      name: "Popping Salad",
      flavor: "bitter",
      kind: "Cooked",
      note: "Made with sea grapes",
      dlc: true,
      recipe: { station: "Chopping Board", ingredients: ["Leaf ×1", "Sea Grapes ×1"], specialty: null, tip: "Bubbly Basin DLC." },
    },
    {
      id: "seaweed-soup",
      name: "Seaweed Soup",
      flavor: "bitter",
      kind: "Cooked",
      note: "Bitter seaweed soup",
      recipe: { station: "Cooking Pot (on Stove)", ingredients: ["Fresh Water ×1", "Seaweed ×1", "Any ×1"], specialty: null },
    },
    {
      id: "popping-soup",
      name: "Popping Soup",
      flavor: "bitter",
      kind: "Cooked",
      note: "Smells of the sea",
      dlc: true,
      recipe: { station: "Cooking Pot (on Stove)", ingredients: ["Fresh Water ×1", "Sea Grapes ×1"], specialty: null, tip: "Bubbly Basin DLC." },
    },
    {
      id: "recycled-bread",
      name: "Recycled Bread",
      flavor: "bitter",
      kind: "Cooked",
      note: "Reused bread",
      recipe: { station: "Bread Oven", ingredients: ["Wheat ×1", "Bread ×1 (any)", "Any ×1"], specialty: "Recycle" },
    },
    {
      id: "bitter-hamburger",
      name: "Bitter Hamburger Steak",
      flavor: "bitter",
      kind: "Cooked",
      note: "Topped with leaves",
      recipe: { station: "Frying Pan (on Stove)", ingredients: ["Bean ×1", "Rawst Berry ×1", "Lum Berry ×1"], specialty: null },
    },
    {
      id: "coffee-parfait-smoothie",
      name: "Coffee Parfait Smoothie",
      flavor: "bitter",
      kind: "Drink",
      note: "Powers up Surf",
      dlc: true,
      recipe: { station: "Blender", ingredients: ["Watermelon Slice ×1", "Moomoo Milk Coffee ×1", "Bread ×1 (any)"], specialty: null, tip: "Bubbly Basin DLC." },
    },

    // Sour
    { id: "aspear-berry", name: "Aspear Berry", flavor: "sour", kind: "Berry", note: "Berry trees", recipe: null },
    { id: "tomato", name: "Tomato", flavor: "sour", kind: "Veggie", note: "Plant & harvest", recipe: null },
    { id: "soda-pop", name: "Soda Pop", flavor: "sour", kind: "Drink", note: "Shop / vending", recipe: null },
    {
      id: "shredded-salad",
      name: "Shredded Salad",
      flavor: "sour",
      kind: "Cooked",
      note: "Finely chopped leaves",
      recipe: { station: "Chopping Board", ingredients: ["Leaf ×1", "Any ×1"], specialty: "Chop" },
    },
    {
      id: "flavourful-soup",
      name: "Flavourful Soup",
      flavor: "sour",
      kind: "Cooked",
      note: "Bursting with flavor",
      recipe: { station: "Cooking Pot (on Stove)", ingredients: ["Fresh Water ×1", "Aspear Berry ×1", "Hamburger Steak ×1 (any)"], specialty: null },
    },
    {
      id: "leppa-bread",
      name: "Leppa Bread",
      flavor: "sour",
      kind: "Cooked",
      note: "Leppa Berry jam bread",
      recipe: { station: "Bread Oven", ingredients: ["Wheat ×1", "Leppa Berry ×1", "Any ×1"], specialty: null },
    },
    {
      id: "tomato-hamburger",
      name: "Tomato Hamburger Steak",
      flavor: "sour",
      kind: "Cooked",
      note: "Sour tomato flavor",
      recipe: { station: "Frying Pan (on Stove)", ingredients: ["Bean ×1", "Tomato ×1", "Any ×2"], specialty: null },
    },
    {
      id: "refreshing-soda-smoothie",
      name: "Refreshing Soda Smoothie",
      flavor: "sour",
      kind: "Drink",
      note: "Powers up Surf",
      dlc: true,
      recipe: { station: "Blender", ingredients: ["Watermelon Slice ×1", "Aspear Berry ×1", "Soda Pop ×1"], specialty: null, tip: "Bubbly Basin DLC." },
    },
  ],

  fossilSets: [
    {
      id: "wing",
      pokemon: "Aerodactyl",
      display: "Wing Fossil Display",
      pieces: [
        { id: "wing-head", name: "Wing Fossil (Head)" },
        { id: "wing-right", name: "Wing Fossil (Right Wing)" },
        { id: "wing-left", name: "Wing Fossil (Left Wing)" },
        { id: "wing-body", name: "Wing Fossil (Body)" },
        { id: "wing-tail", name: "Wing Fossil (Tail)" },
      ],
    },
    {
      id: "skull",
      pokemon: "Cranidos",
      display: "Skull Fossil Display",
      pieces: [{ id: "skull", name: "Skull Fossil" }],
    },
    {
      id: "headbutt",
      pokemon: "Rampardos",
      display: "Headbutt Fossil Display",
      pieces: [
        { id: "headbutt-head", name: "Headbutt Fossil (Head)" },
        { id: "headbutt-body", name: "Headbutt Fossil (Body)" },
        { id: "headbutt-tail", name: "Headbutt Fossil (Tail)" },
      ],
    },
    {
      id: "armor",
      pokemon: "Shieldon",
      display: "Armor Fossil Display",
      pieces: [{ id: "armor", name: "Armor Fossil" }],
    },
    {
      id: "shield",
      pokemon: "Bastiodon",
      display: "Shield Fossil Display",
      pieces: [
        { id: "shield-head", name: "Shield Fossil (Head)" },
        { id: "shield-body", name: "Shield Fossil (Body)" },
        { id: "shield-tail", name: "Shield Fossil (Tail)" },
      ],
    },
    {
      id: "jaw",
      pokemon: "Tyrunt",
      display: "Jaw Fossil Display",
      pieces: [{ id: "jaw", name: "Jaw Fossil" }],
    },
    {
      id: "despot",
      pokemon: "Tyrantrum",
      display: "Despot Fossil Display",
      pieces: [
        { id: "despot-head", name: "Despot Fossil (Head)" },
        { id: "despot-body", name: "Despot Fossil (Body)" },
        { id: "despot-legs", name: "Despot Fossil (Legs)" },
        { id: "despot-tail", name: "Despot Fossil (Tail)" },
      ],
    },
    {
      id: "sail",
      pokemon: "Amaura",
      display: "Sail Fossil Display",
      pieces: [{ id: "sail", name: "Sail Fossil" }],
    },
    {
      id: "tundra",
      pokemon: "Aurorus",
      display: "Tundra Fossil Display",
      pieces: [
        { id: "tundra-head", name: "Tundra Fossil (Head)" },
        { id: "tundra-body", name: "Tundra Fossil (Body)" },
        { id: "tundra-legs", name: "Tundra Fossil (Legs)" },
      ],
    },
  ],

  /**
   * Dream Islands — doll → materials → legendary (if any).
   * Sources: Serebii focus list; Thonky / Games Wiki / Polygon for legendaries.
   * Legendaries are a chance find (often in caves), not guaranteed each visit.
   */
  dreamIslands: [
    {
      id: "eevee",
      doll: "Eevee Doll",
      island: "Wasteland Dream Island",
      biome: "Withered Wasteland",
      materials: ["Leppa Berry", "Vine Rope", "Glowing Mushrooms"],
      legendary: "Suicune",
      legendaryNote: "Search deep caves / ice room — chance spawn.",
    },
    {
      id: "pikachu",
      doll: "Pikachu Doll",
      island: "Ocean Dream Island",
      biome: "Bleak Beach",
      materials: ["Twine", "Sea Glass Fragments", "Seashell"],
      legendary: "Raikou",
      legendaryNote: "Cave room with metal blocks — may need story encounter first.",
    },
    {
      id: "clefairy",
      doll: "Clefairy Doll",
      island: "Rock Peak Dream Island",
      biome: "Rocky Ridges (exterior)",
      materials: ["Cave Mushrooms", "Copper Ore", "Limestone"],
      legendary: null,
      legendaryNote: "No legendary confirmed — materials / cave run.",
    },
    {
      id: "arcanine",
      doll: "Arcanine Doll",
      island: "Volcanic Dream Island",
      biome: "Rocky Ridges (interior)",
      materials: ["Iron Ore", "Gold Ore", "Glowing Stone"],
      legendary: "Entei",
      legendaryNote: "Cave room surrounded by lava rocks — chance spawn.",
    },
    {
      id: "dragonite",
      doll: "Dragonite Doll",
      island: "Sky Dream Island",
      biome: "Sparkling Skylands",
      materials: ["Wastepaper", "PokéMetal", "Crystal Fragment"],
      legendary: "Mewtwo",
      legendaryNote: "Building-like cave room — may need story encounter first.",
    },
    {
      id: "starmie",
      doll: "Starmie Doll",
      island: "Basin Dream Island",
      biome: "Water / basin",
      materials: ["Sea Grapes", "Small Coral", "Grubby Pearl"],
      legendary: "Phione",
      legendaryNote: "Underwater ruins — chance spawn.",
      dlc: true,
    },
    {
      id: "ditto",
      doll: "Ditto Doll",
      island: "Random Dream Island",
      biome: "Varies",
      materials: ["Random (any island’s materials)"],
      legendary: "Random",
      legendaryNote: "Rolls a random unlocked island — can include legendaries.",
    },
    {
      id: "substitute",
      doll: "Substitute Doll",
      island: "Random Dream Island",
      biome: "Varies",
      materials: ["Random (any island’s materials)"],
      legendary: "Random",
      legendaryNote: "Same as Ditto Doll — random destination each visit.",
    },
  ],
};
